#!/bin/bash
    ORG_ORIGEN='juancobandor@empathetic-narwhal-au1pri.com' #SALTO-DEV
    ORG_DESTINO='juancobandor@empathetic-narwhal-au1pri.com' #SALTO-UAT
    XML_COMPONENTES='package.xml'
    YAML_COMPONENTES='package.yaml'
while :
do
    #Menu
    clear
    echo -e "\e[1;32m"
    echo " MENU SCRIPT V.1 "
    echo ""
    echo "1. Retrieve XML"
    echo "2. Deploy XML"
    echo "3. Run Test Deploy XML"
    echo "4. Retrieve YAML"
    echo "5. Deploy YAML"
    echo "6. Salir"
    echo ""
    #Escoger menu
    echo -n "Escoger opción: "
    read opcion
    #Seleccion de menu
case $opcion in
1) 
    echo "Inicia proceso retrieve XML"
    # Execute Salesforce CLI command
    echo "Retrieve to Salesforce..."
    sfdx force:config:set defaultusername=${ORG_ORIGEN}
    cd ..
    sf project retrieve start --manifest manifest/${XML_COMPONENTES}
    cd scripts/
    echo "Enter para volver al menú"
    
read foo
;;
2) 
    echo "Inicia proceso deploy XML"
    # Execute Salesforce CLI command
    echo "Deploy to Salesforce..."
    sfdx force:config:set defaultusername=${ORG_DESTINO} 
    cd ..
    sf project deploy start --manifest manifest/${XML_COMPONENTES}
    sfdx force:config:set defaultusername=${ORG_ORIGEN}
    cd scripts/
    echo "Enter para volver al menú"
read foo
;;

3) 
    echo "Inicia Run Test deploy XML"
    # Execute Salesforce CLI command
    echo "Run Test Deploy to Salesforce..."
    sfdx force:config:set defaultusername=${ORG_DESTINO} 
    cd ..
    sfdx force:source:deploy --checkonly -x manifest/${XML_COMPONENTES} -u ${ORG_DESTINO} --testlevel RunLocalTests
    sfdx force:config:set defaultusername=${ORG_ORIGEN}
    cd scripts/
    echo "Enter para volver al menú"
read foo
;;

4) 
    echo "Inicia proceso retrieve YAML"
    # Execute Salesforce CLI command
    echo "Retrieve to Salesforce..."
    sfdx force:config:set defaultusername=${ORG_ORIGEN}
    cd ..
    vlocity -sfdx.username ${ORG_ORIGEN} -job manifest/${YAML_COMPONENTES} packExport
    cd scripts/
    echo "Enter para volver al menú"
read foo
;;

5) 
    echo "Inicia proceso deploy YAML"
    # Execute Salesforce CLI command
    echo "Deploy to Salesforce..."
    sfdx force:config:set defaultusername=${ORG_DESTINO} 
    cd ..
    vlocity -sfdx.username ${ORG_DESTINO} -job manifest/${YAML_COMPONENTES} packDeploy
    sfdx force:config:set defaultusername=${ORG_ORIGEN}
    cd scripts/
    echo "Enter para volver al menú"
read foo
;;

6)

exit 0
cd scripts/
;;
#Alerta
*)echo "Opción inválida..."
sleep 1
esac
done